In [1]:
import numpy

In [2]:
A = numpy.array(
    [
        [6.7, 1.3, 0.6, 0.7],
        [0.1, 5.5, 0.4, 2.4],
        [1.1, 0.8, 4.5, 1.7],
        [0.0, 1.5, 3.4, 7.5],
    ]
)

b = numpy.array([1.1, 2.3, 3.3, 3.9])

In [3]:
# Print row 1

print(A[0, :])

[6.7 1.3 0.6 0.7]


In [4]:
# Print columns 1 and 3

print(A[:, [0, 2]])

[[6.7 0.6]
 [0.1 0.4]
 [1.1 4.5]
 [0.  3.4]]


In [6]:
# Print all values greater than 2

print(A[A > 2])

[6.7 5.5 2.4 4.5 3.4 7.5]


In [7]:
# Print the diagonal of A

print(numpy.diag(A))

[6.7 5.5 4.5 7.5]


In [8]:
x = numpy.linalg.solve(A, b)

In [9]:
numpy.dot(A, x)

array([1.1, 2.3, 3.3, 3.9])

In [10]:
numpy.transpose(A)

array([[6.7, 0.1, 1.1, 0. ],
       [1.3, 5.5, 0.8, 1.5],
       [0.6, 0.4, 4.5, 3.4],
       [0.7, 2.4, 1.7, 7.5]])

In [11]:
numpy.linalg.inv(A)

array([[ 0.15267508, -0.03365026, -0.01778   ,  0.00054854],
       [-0.00906001,  0.19788853,  0.03719385, -0.07090934],
       [-0.04391535, -0.0144834 ,  0.26880108, -0.05219479],
       [ 0.02172029, -0.0330119 , -0.12929526,  0.17117684]])

In [12]:
B = numpy.ravel(A)

In [13]:
B

array([6.7, 1.3, 0.6, 0.7, 0.1, 5.5, 0.4, 2.4, 1.1, 0.8, 4.5, 1.7, 0. ,
       1.5, 3.4, 7.5])

In [14]:
B.reshape(A.shape)

array([[6.7, 1.3, 0.6, 0.7],
       [0.1, 5.5, 0.4, 2.4],
       [1.1, 0.8, 4.5, 1.7],
       [0. , 1.5, 3.4, 7.5]])